### ISSUE TITLE
No dataRate in packet

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/android-sdk#2]
The Packet class does not expose the dataRate field.

**Comment by ticofab** [comment]
Thanks for reporting, fixing it!

**Comment by jpmeijers** [comment]
Close to the same area in the code I have a similar issue. Packet.setDataPlain is never called from MqttPacketConverter.

**Comment by ticofab** [comment]
The problem is that currently there is a discrepancy between the information sent by the REST api and the MQTT api. They basically send different things, and that's why there are two different converters :/ This issue won't be fixed as efforts are focused on building the new backend.

**Comment by jpmeijers** [comment]
Understandable. Thanks for the fixes and answers.
