### ISSUE TITLE
JSON data set to RSSI value

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/android-sdk#3]
MqttPacketConverter, line 47-49:
        if (jsonObj.has(JSON_KEY_RSSI)) {
            builder.setDataJson(jsonObj.getString(JSON_KEY_RSSI));
        }

builder.setDataJson should not take RSSI, but rather the raw ascii json string.

**Comment by ticofab** [comment]
Thanks for reporting!
